<?php
declare( strict_types=1 );

namespace PowerBoard\Model;

use PowerBoard\Enums\AvailablePaymentMethods\PBAvailablePaymentMethodsEnum;
use PowerBoard\Enums\PaymentNotification\PBPaymentNotificationEnum;
use PowerBoard\Helpers\Util\LoggerHelper;

class IPN {

	protected const ALLOWED_IPN_OBJECT_TYPES = [ 'payment', 'refund' ];

	/**
	 * Charge generated by PowerBoard.
	 *
	 * @var Charge
	 */
	protected $charge;

	/**
	 * Identifier of the payment intent associated with the charge.
	 *
	 * @var string
	 */
	protected $intent_id;

	/**
	 * WooCommerce order ID associated with this notification.
	 *
	 * @var int
	 */
	protected $order_id;

	/**
	 * Error message returned by the gateway when a payment fails.
	 * Empty string on success.
	 *
	 * @var string
	 */
	protected $failure_message;

	/**
	 * Transaction amount in major currency units (e.g., 10.00).
	 *
	 * @var float
	 */
	protected $amount;

	/**
	 * ISO 4217 currency code for the transaction (e.g., 'USD', 'EUR').
	 *
	 * @var string
	 */
	protected $currency;

	/**
	 * Timestamp when the event occurred.
	 *
	 * @var int
	 */
	protected $timestamp;

	/**
	 * Payment method used for the transaction (e.g., 'cc', 'applepay', 'googlepay').
	 *
	 * @var string
	 */
	protected $payment_method;

	/**
	 * Type of the object associated with the event (e.g., 'payment').
	 *
	 * @var string
	 */
	protected $object_type;

	/**
	 * Unique identifier for this IPN event, used for idempotency and deduplication.
	 *
	 * @var string
	 */
	protected $event_id;

	/**
	 * Normalized event name mapped via PBPaymentNotificationEnum (e.g., 'payment_succeeded', 'payment_failed').
	 *
	 * @var string
	 */
	protected $event;

	/**
	 * Whether the charge has been paid successfully.
	 *
	 * @var bool
	 */
	protected $is_paid;

	public function __construct( $data ) {

		if ( ! $this->validate_ipn_response_data( $data ) ) {
			LoggerHelper::log_callback_event( 'Invalid IPN payload: missing or invalid fields.', [], 'error' );
			wp_send_json_error(
				[ 'message' => 'Invalid IPN payload: missing or invalid fields.' ],
				400
			);
		}

		// Map according to actual PowerBoard IPN format
		$this->charge          = new Charge( $data );
		$this->intent_id       = (string) $data['intent_id'] ?? null;
		$this->order_id        = (int) $data['reference']?? null;
		$this->failure_message = isset( $data['error'] ) ? (string) $data['error']['err_message'] : null;
		$this->amount          = (float) $data['amount'] ?? 0;
		$this->currency        = (string) $data['currency'] ?? null;
		$this->timestamp       = (int) $data['timestamp'] ?? null;
		$this->object_type     = (string) $data['object_type'] ?? null;
		$this->event_id        = (string) $data['event_id']?? null;
		$this->event           = (string) PBPaymentNotificationEnum::get_ipn_event( $data['event'] );
		$this->is_paid         = (bool) $data['is_paid'] ?? null;
	}

	/**
	 * Validate IPN response data
	 *
	 * @param array $data
	 * @return bool
	 */
	public function validate_ipn_response_data( $data ) {

		if ( in_array( PBPaymentNotificationEnum::get_ipn_event( $data['event'] ), [ PBPaymentNotificationEnum::PAYMENT_FAILED, PBPaymentNotificationEnum::CHECKOUT_FAILED, PBPaymentNotificationEnum::CHECKOUT_CANCELLED ], true ) ) {
			$data['charge']['_id'] = $data['error']['charge_id'];
		}

		return $this->is_valid_string( $data['charge']['_id'] )
			&& $this->is_valid_string( $data['intent_id'] )
			&& $this->is_valid_int( (int) $data['reference'] )
			&& $this->is_valid_amount( $data['amount'] )
			&& !empty( $data['currency'] )
			&& $this->is_valid_int( $data['timestamp'] )
			&& $this->validate_ipn_object_type( $data['object_type'] )
			&& $this->is_valid_string( $data['event_id'] )
			&& $this->validate_ipn_event( PBPaymentNotificationEnum::get_ipn_event( $data['event'] ) );
	}

	/**
	 * Check if value is a valid string.
	 *
	 * @param string $value
	 * @return bool
	 */
	private function is_valid_string( $value ): bool {
		return !empty( $value ) && is_string( $value );
	}

	/**
	 * Check if value is a valid integer.
	 *
	 * @param int $value
	 * @return bool
	 */
	private function is_valid_int( $value ): bool {
		return !empty( $value ) && is_int( $value );
	}

	/**
	 * Check if value is a valid amount.
	 *
	 * @param float $value
	 * @return bool
	 */
	private function is_valid_amount( $value ): bool {
		return isset( $value ) && is_numeric( $value ) && $value > 0;
	}

	/**
	 * Check if value is a valid IPN object type.
	 *
	 * @param string $obj_type
	 * @return bool
	 */
	private function validate_ipn_object_type( $obj_type ): bool {
		return in_array( $obj_type, self::ALLOWED_IPN_OBJECT_TYPES, true );
	}

	/**
	 * Check if value is a valid IPN event.
	 *
	 * @param string $event
	 * @return bool
	 */
	private function validate_ipn_event( $event ): bool {
		return in_array( $event, PBPaymentNotificationEnum::EVENTS, true );
	}

	public function get_charge(): ?Charge {
		return $this->charge;
	}

	public function get_intent_id(): ?string {
		return $this->intent_id;
	}

	public function get_order_id(): ?int {
		return $this->order_id;
	}

	public function get_failure_message(): ?string {
		return $this->failure_message;
	}

	public function get_amount(): ?float {
		return $this->amount;
	}

	public function get_currency(): ?string {
		return $this->currency;
	}

	public function get_timestamp(): ?int {
		return $this->timestamp;
	}

	public function get_payment_method(): ?string {
		return $this->payment_method;
	}

	public function get_object_type(): ?string {
		return $this->object_type;
	}

	public function get_event_id(): ?string {
		return $this->event_id;
	}

	public function get_event(): ?string {
		return $this->event;
	}

	public function get_is_paid(): ?bool {
		return $this->is_paid;
	}
}
