<?php
declare( strict_types=1 );

namespace PowerBoard\Model;

use PowerBoard\Enums\AvailablePaymentMethods\PBAvailablePaymentMethodsEnum;
use PowerBoard\Enums\PaymentNotification\PBPaymentNotificationEnum;
use PowerBoard\Helpers\Util\LoggerHelper;

class IPN {

	protected const ALLOWED_IPN_OBJECT_TYPES = [ 'payment', 'refund' ];

	/**
	 * Charge generated by PowerBoard.
	 *
	 * @var Charge
	 */
	protected $charge;

	/**
	 * Identifier of the payment intent associated with the charge.
	 *
	 * @var string
	 */
	protected $intent_id;

	/**
	 * WooCommerce order ID associated with this notification.
	 *
	 * @var int
	 */
	protected $order_id;

	/**
	 * Error message returned by the gateway when a payment or refund fails.
	 * Empty string on success.
	 *
	 * @var string
	 */
	protected $failure_message;

	/**
	 * Transaction amount in major currency units (e.g., 10.00).
	 *
	 * @var float
	 */
	protected $amount;

	/**
	 * ISO 4217 currency code for the transaction (e.g., 'USD', 'EUR').
	 *
	 * @var string
	 */
	protected $currency;

	/**
	 * Total amount that has been refunded for this charge so far, in major currency units.
	 *
	 * @var float
	 */
	protected $amount_refunded;

	/**
	 * Timestamp when the event occurred.
	 *
	 * @var int
	 */
	protected $timestamp;

	/**
	 * Payment method used for the transaction (e.g., 'cc', 'applepay', 'googlepay').
	 *
	 * @var string
	 */
	protected $payment_method;

	/**
	 * Type of the object associated with the event (e.g., 'payment' or 'refund').
	 *
	 * @var string
	 */
	protected $object_type;

	/**
	 * Unique identifier for this IPN event, used for idempotency and deduplication.
	 *
	 * @var string
	 */
	protected $event_id;

	/**
	 * Normalized event name mapped via PBPaymentNotificationEnum (e.g., 'payment_failed', 'payment_refunded').
	 *
	 * @var string
	 */
	protected $event;

	/**
	 * Whether the charge has been paid successfully.
	 *
	 * @var bool
	 */
	protected $is_paid;

	public function __construct( $data ) {

		if ( ! $this->validate_ipn_response_data( $data ) ) {
			wp_send_json_error(
				[ 'message' => 'Invalid IPN payload: missing or invalid fields.' ],
				400
			);
		}

		// Map according to actual PowerBoard IPN format
		// See docs/ipn.json for structure
		$this->charge_id       = $data['id'] ?? '';  // Payment ID is the charge ID
		$this->intent_id       = ''; // Not provided in IPN, leave empty
		$this->order_id        = isset( $data['metadata']['order_id'] ) ? (int) $data['metadata']['order_id'] : null;
		$this->failure_message = $data['failure']['message'] ?? '';
		// Convert amount from cents to major currency units
		$this->amount          = isset( $data['amount'] ) ? ( (float) $data['amount'] / 100 ) : 0.0;
		$this->currency        = $data['currency'] ?? '';
		$this->amount_refunded = isset( $data['amount_refunded'] ) ? ( (float) $data['amount_refunded'] / 100 ) : 0.0;
		$this->timestamp       = $data['created_at'] ?? time();
		$this->payment_method  = PBAvailablePaymentMethodsEnum::get_available_payment_method( $data['payment_method']['type'] ?? '' );
		$this->object_type     = $data['object'] ?? '';  // 'payment' or 'refund'
		// Generate event_id from payment ID and timestamp as PowerBoard doesn't send separate event_id
		$this->event_id        = $this->charge_id . '_' . $this->timestamp;
		// Derive event from payment state flags
		$this->event           = $this->derive_event_from_payment_state( $data );

		$this->charge          = new Charge( $data );
		$this->intent_id       = (string) $data['intent_id'] ?? null;
		$this->order_id        = (int) $data['order_id']?? null;
		$this->failure_message = (string) $data['failure_message'] ?? null;
		$this->amount          = (float) $data['amount'] ?? null;
		$this->currency        = (string) $data['currency'] ?? null;
		$this->timestamp       = (int) $data['timestamp'] ?? null;
		$this->payment_method  = (string) PBAvailablePaymentMethodsEnum::get_available_payment_method( $data['payment_method'] );
		$this->object_type     = (string) $data['event_type'] ?? null;
		$this->event_id        = (string) $data['event_id']?? null;
		$this->event           = (string) PBPaymentNotificationEnum::get_ipn_event( $data['event'] );
		$this->is_paid         = (bool) $data['is_paid'] ?? null;
	}

	/**
	 * Validate IPN response data
	 *
	 * @param array $data
	 * @return bool
	 */
	public function validate_ipn_response_data( $data ) {
		return $this->is_valid_string( $data['charge_id'] )
			&& $this->is_valid_string( $data['intent_id'] )
			&& $this->is_valid_int( (int) $data['order_id'] )
			&& $this->is_valid_amount( $data['amount'] )
			&& !empty( $data['currency'] )
			&& $this->is_valid_int( $data['timestamp'] )
			&& $this->validate_payment_method( PBAvailablePaymentMethodsEnum::get_available_payment_method( $data['payment_method'] ) )
			&& $this->validate_ipn_object_type( $data['event_type'] )
			&& $this->is_valid_string( $data['event_id'] )
			&& $this->validate_ipn_event( PBPaymentNotificationEnum::get_ipn_event( $data['event'] ) );
	}


	/**
	 * Check if value is a valid string.
	 *
	 * @param string $value
	 * @return bool
	 */
	private function is_valid_string( $value ): bool {
		return !empty( $value ) && is_string( $value );
	}

	/**
	 * Check if value is a valid integer.
	 *
	 * @param int $value
	 * @return bool
	 */
	private function is_valid_int( $value ): bool {
		return !empty( $value ) && is_int( $value );
	}

	/**
	 * Check if value is a valid amount.
	 *
	 * @param float $value
	 * @param bool $allow_zero
	 * @return bool
	 */
	private function is_valid_amount( $value, $allow_zero = false ): bool {
		return isset( $value ) && is_numeric( $value ) && ( $value > 0 || ( $allow_zero && (int) $value === 0 ) );
	}

	/**
	 * Check if value is a valid IPN object type.
	 *
	 * @param string $obj_type
	 * @return bool
	 */
	private function validate_ipn_object_type( $obj_type ): bool {
		return in_array( $obj_type, self::ALLOWED_IPN_OBJECT_TYPES, true );
	}

	/**
	 * Check if value is a valid IPN event.
	 *
	 * @param string $event
	 * @return bool
	 */
	private function validate_ipn_event( $event ): bool {
		return in_array( $event, PBPaymentNotificationEnum::EVENTS, true );
	}

	/**
	 * Check if value is a valid Payment Method.
	 *
	 * @param string $payment_method
	 * @return bool
	 */
	private function validate_payment_method( $payment_method ): bool {
		return in_array( $payment_method, PBAvailablePaymentMethodsEnum::PAYMENT_METHODS, true );
	}

	public function get_charge(): ?Charge {
		return $this->charge;
	}

	public function get_intent_id(): ?string {
		return $this->intent_id;
	}

	public function get_order_id(): ?int {
		return $this->order_id;
	}

	public function get_failure_message(): ?string {
		return $this->failure_message;
	}

	public function get_amount(): ?float {
		return $this->amount;
	}

	public function get_currency(): ?string {
		return $this->currency;
	}

	public function get_timestamp(): ?int {
		return $this->timestamp;
	}

	public function get_payment_method(): ?string {
		return $this->payment_method;
	}

	public function get_object_type(): ?string {
		return $this->object_type;
	}

	public function get_event_id(): ?string {
		return $this->event_id;
	}

	public function get_event(): ?string {
		return $this->event;
	}

	public function get_is_paid(): ?bool {
		return $this->is_paid;
	}
	/**
	 * Derive event name from PowerBoard payment state flags
	 *
	 * @param array $data PowerBoard IPN payload
	 * @return string Event name
	 */
	private function derive_event_from_payment_state( array $data ): string {
		$object_type = $data['object'] ?? '';

		// Handle refund object type
		if ( $object_type === 'refund' ) {
			return PBPaymentNotificationEnum::PAYMENT_REFUNDED;
		}

		// Handle payment object type based on state flags
		$is_paid = $data['is_paid'] ?? false;
		$is_refunded = $data['is_refunded'] ?? false;
		$is_pending = $data['payment_method']['is_pending'] ?? false;
		$failure_message = $data['failure']['message'] ?? '';

		// Check for failure first
		if ( ! empty( $failure_message ) ) {
			return PBPaymentNotificationEnum::PAYMENT_FAILED;
		}

		// Check for refunded state
		if ( $is_refunded ) {
			return PBPaymentNotificationEnum::PAYMENT_REFUNDED;
		}

		// Check for successful payment
		if ( $is_paid ) {
			return PBPaymentNotificationEnum::PAYMENT_SUCCEEDED;
		}

		// Check for pending state
		if ( $is_pending ) {
			return PBPaymentNotificationEnum::PAYMENT_CREATED;
		}

		// Default to payment created
		return PBPaymentNotificationEnum::PAYMENT_CREATED;
	}
}
