<?php
declare( strict_types=1 );

namespace PowerBoard\Model;

use PowerBoard\Enums\AvailablePaymentMethods\PBAvailablePaymentMethodsEnum;
use PowerBoard\Enums\PaymentNotification\PBPaymentNotificationEnum;
use PowerBoard\Helpers\Util\LoggerHelper;

class IPN {

	/**
	 * Unique identifier of the charge/transaction generated by PowerBoard.
	 *
	 * @var string
	 */
	protected $charge_id;

	/**
	 * Identifier of the payment intent associated with the charge.
	 *
	 * @var string
	 */
	protected $intent_id;

	/**
	 * WooCommerce order ID associated with this notification.
	 *
	 * @var int
	 */
	protected $order_id;

	/**
	 * Error message returned by the gateway when a payment or refund fails.
	 * Empty string on success.
	 *
	 * @var string
	 */
	protected $failure_message;

	/**
	 * Transaction amount in major currency units (e.g., 10.00).
	 *
	 * @var float
	 */
	protected $amount;

	/**
	 * ISO 4217 currency code for the transaction (e.g., 'USD', 'EUR').
	 *
	 * @var string
	 */
	protected $currency;

	/**
	 * Total amount that has been refunded for this charge so far, in major currency units.
	 *
	 * @var float
	 */
	protected $amount_refunded;

	/**
	 * Timestamp when the event occurred.
	 *
	 * @var int
	 */
	protected $timestamp;

	/**
	 * Payment method used for the transaction (e.g., 'cc', 'applepay', 'googlepay').
	 *
	 * @var string
	 */
	protected $payment_method;

	/**
	 * Type of the object associated with the event (e.g., 'payment' or 'refund').
	 *
	 * @var string
	 */
	protected $object_type;

	/**
	 * Unique identifier for this IPN event, used for idempotency and deduplication.
	 *
	 * @var string
	 */
	protected $event_id;

	/**
	 * Normalized event name mapped via PBPaymentNotificationEnum (e.g., 'payment_failed', 'payment_refunded').
	 *
	 * @var string
	 */
	protected $event;


	public function map_powerboard_ipn_response( $data ) {
		$data = json_decode( $data, true );

		$this->charge_id       = $data['charge_id'];
		$this->intent_id       = $data['intent_id'];
		$this->order_id        = $data['order_id'];
		$this->failure_message = $data['failure_message'] ?? '';
		$this->amount          = $data['amount'];
		$this->currency        = $data['currency'];
		$this->amount_refunded = $data['amount_refunded'] ?? 0;
		$this->timestamp       = $data['timestamp'];
		$this->payment_method  = PBAvailablePaymentMethodsEnum::get_available_payment_method( $data['payment_method'] );
		$this->object_type     = $data['event_type'];
		$this->event_id        = $data['event_id'];
		$this->event           = PBPaymentNotificationEnum::get_ipn_event( $data['event'] );

		LoggerHelper::log(
			'map_ipn_response',
			'info',
			[
				'charge_id'       => $this->charge_id,
				'intent_id'       => $this->intent_id,
				'order_id'        => $this->order_id,
				'failure_message' => $this->failure_message,
				'amount'          => $this->amount,
				'currency'        => $this->currency,
				'amount_refunded' => $this->amount_refunded,
				'timestamp'       => $this->timestamp,
				'payment_method'  => $this->payment_method,
				'object_type'     => $this->object_type,
				'event_id'        => $this->event_id,
				'event'           => $this->event,
			]
		);
	}

	public function get_charge_id(): ?string {
		return $this->charge_id;
	}

	public function get_intent_id(): ?string {
		return $this->intent_id;
	}

	public function get_order_id(): ?int {
		return $this->order_id;
	}

	public function get_failure_message(): ?string {
		return $this->failure_message;
	}

	public function get_amount(): ?float {
		return $this->amount;
	}

	public function get_currency(): ?string {
		return $this->currency;
	}

	public function get_amount_refunded(): ?float {
		return $this->amount_refunded;
	}

	public function get_timestamp(): ?int {
		return $this->timestamp;
	}

	public function get_payment_method(): ?string {
		return $this->payment_method;
	}

	public function get_object_type(): ?string {
		return $this->object_type;
	}

	public function get_event_id(): ?string {
		return $this->event_id;
	}

	public function get_event(): ?string {
		return $this->event;
	}
}
